import numpy as np
from stable_baselines3 import PPO
import os
from typing import Optional, Dict, Tuple

class RLAgentService:
    def __init__(self):
        self.model = None
        # Path to the zip file generated by your Notebook
        self.model_path = os.path.join(os.path.dirname(__file__), "ppo_literature_agent.zip")
        self.load_model()
        
    def load_model(self):
        try:
            if os.path.exists(self.model_path):
                self.model = PPO.load(self.model_path)
                print(f"✅ RL Model loaded from {self.model_path}")
            else:
                print(f"⚠️ RL Model not found at {self.model_path}. Agent will use random actions.")
        except Exception as e:
            print(f"❌ Error loading RL model: {e}")

    def predict_action(self, text_difficulty: float, student_focus: float, disability_profile: Optional[Dict]) -> Tuple[int, str]:
        if not self.model:
            return 0, "Default"
            
        disability_val = 0.0
        if disability_profile:
            disabs = disability_profile.get("disabilities", [])
            if "dyslexia" in disabs: disability_val = 0.5
            elif "adhd" in disabs: disability_val = 1.0
            
        # FIX: State is now 5 values!
        # [Difficulty, Focus, Disability, Fatigue (0), History (0.5)]
        # We initialize Fatigue at 0 and History at neutral for new requests
        obs = np.array([
            text_difficulty, 
            student_focus, 
            disability_val, 
            0.0, 
            0.5
        ], dtype=np.float32)
        
        action, _ = self.model.predict(obs, deterministic=True)
        
        action_map = {
            0: "Keep Original",
            1: "Light Simplification",
            2: "Heavy Simplification (Summary)", # Updated label
            3: "Enable TTS & Highlights"
        }
        
        return int(action), action_map.get(int(action), "Unknown")